language: generic
sudo: false # use container based build

# set clone depth to false to make sure that conda build can write the
# correct GIT_BUILD_STR
git:
  depth: false

env:
    matrix:
        # python 3.8
        - PYTHON_VERSION=3.8 DEPLOY_CONDA=true
        - PYTHON_VERSION=3.8 XARRAY_VERSION=0.14
        - PYTHON_VERSION=3.8 USE_PIP=true
        # python 3.7
        - PYTHON_VERSION=3.7 DEPLOY_CONDA=true
        - PYTHON_VERSION=3.7 XARRAY_VERSION=0.14
        - PYTHON_VERSION=3.7 XARRAY_VERSION=0.13
        - PYTHON_VERSION=3.7 XARRAY_VERSION=0.12
    global:
        - secure: "Bb2eZLr3mAb32loic84gcpPpFKHZPdOr3LLmXxj+jRO/2W/5FvWznGgMIcGeH1f4EHtjbafgY8P2ybzHuQOZnV40rpJ8KGnNF5MT8RkjsT2OVEe+SojpdZ3cxMWqaXrn+FBrhov7Uva1QYrsZmDtkPEcPiWPpNlrqeeIuWP/HfaO/SDB0Mc2gMPmTb/buwqoXycRBAaEE8jQm9QMuq0NVP1oZlTeGt5wr8TFMgIWRpGvZP5yJNGszaTKDxcE/mhmUTjOMWFgcPBT3t5meZ8SeLcgH9+PSNdsOGV2pGG8uxAssSy3H9ZK6zkdEu2609TP17ojjinO2DiqvKc6128LIwva2/iUR+MXT5mJ2KOzUZtGfUA2qGyc7UUwT3G922LyDo7vg/msSTykGo4vc+bpf8jBGW2tijhV5LFYwfP2M6MBloH2cUoleRkpmba2Zz7aC0IyYHL3dfSgwMN87FHuKsYkvIT8JXpsxp/KMrVmMZ4ugBN+QVUU+AgLy8psjbBXYrqwItU/p7jxM2uIW35y+nAdEkkn+6olWhTPCtF0cVxZZxelk/4ca3oCWWJmIy6Irc/Nz8f9fyUGFYGy8Wdw8wHZliSoXiW+QDs6Gm5lVxMNNvspwhC6PlBgMQk+/+XBOKon0UzH1FfWKajSG1Cy7aiQ8Y9F0JinIkZoE/lohOI="

os:
    - linux
    - osx

services:
    - xvfb

matrix:
    allow_failures:
        - env: PYTHON_VERSION=3.8 USE_PIP=true DEPLOY_CONDA=false

before_install:
    - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then export DEPLOY_CONDA=false; fi
    # Remove homebrew.
    - |
      if [[ $TRAVIS_OS_NAME == "osx" ]]; then
          echo ""
          echo "Removing homebrew from Travis CI to avoid conflicts."
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
          chmod +x ~/uninstall_homebrew
          ~/uninstall_homebrew -fq
          rm ~/uninstall_homebrew
      fi
    # define functions to unset and reset encrypted variables
    - function unset_secure {
          CONDA_TOKEN_SAVE=$CONDA_REPO_TOKEN;
          unset CONDA_REPO_TOKEN;
          }
    - function reset_secure {
          export CONDA_REPO_TOKEN=$CONDA_TOKEN_SAVE;
          }
    - unset_secure
    # increase open files limit
    - ulimit -a
    - ulimit -Sn 10000
    - ulimit -a
      # select the os name for the conda installer
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          OS_NAME=MacOSX;
      else
          OS_NAME=Linux;
      fi
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-${OS_NAME}-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -bp $HOME/miniconda3
    - source $HOME/miniconda3/bin/activate root
    - hash -r
    - reset_secure

before_script:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
          export "DISPLAY=:99.0";
          sh -e /etc/init.d/xvfb start;
          sleep 3;
      fi

install:
    # unset the global CONDA_REPO_TOKEN variable because it is not needed
    # during the tests. This decreases the vulnerability
    - unset_secure
    - |
        echo ""
        echo "Configuring conda."
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda config --add channels chilipp
        conda update -q conda
        conda install conda-build anaconda-client conda-verify
    - if [[ $TRAVIS_TAG == "" ]]; then
        export GIT_BRANCH=$TRAVIS_BRANCH;
        conda config --add channels chilipp/label/${TRAVIS_BRANCH};
      fi
    - python ci/setup_append.py ci/conda-recipe xarray=${XARRAY_VERSION}
    - if [[ $USE_PIP == true ]]; then
        python -m pip install . -r ci/requirements.txt;
      fi
    - conda info -a
    - conda list
    - reset_secure
script:
    - unset_secure
    # install conda
    - if [[ $USE_PIP == true ]]; then
          pytest -v --cov=psyplot && codecov;
      else
          conda build ci/conda-recipe --python $PYTHON_VERSION;
      fi
    # export the pw to make it available for the deploy
    - reset_secure
    # deploy here (don't use travis deploy because it requires homebrew)
    - if [[ $DEPLOY_CONDA == "true" && $USE_PIP == "false" && $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_REPO_SLUG == "Chilipp/psyplot" ]]; then
          ci/deploy_anaconda.py;
      fi
