name: psyplot_docs
channels:
    - chilipp/label/dev
    - chilipp/label/master
    - chilipp
dependencies:
    - python=3.7
    - dask
    - xarray
    - netCDF4
    - matplotlib=3.0.*
    - seaborn
    - ipython
    - nbconvert
    - jupyter_client
    - ipykernel
    - sphinx
    - psy-maps
    - pip
    - pip:
        - autodocsumm
        - cdo
        - sphinx-argparse
        - sphinx-nbexamples
