name: psyplot_docs
channels:
    - psyplot/label/gh-migration
    - psyplot/label/dev
    - psyplot/label/master
    - psyplot
    - chilipp/label/conda-forge
dependencies:
    - python>3.5
    - dask
    - xarray
    - netCDF4
    - matplotlib
    - seaborn
    - ipython
    - nbconvert
    - jupyter_client
    - ipykernel
    - sphinx
    - psy-maps
    - pip
    - pip:
        - autodocsumm
        - cdo
        - sphinx-argparse
        - sphinx-nbexamples
