name: psyplot_docs
channels:
    - psyplot/label/gh-migration
    - psyplot/label/dev
    - psyplot/label/master
    - psyplot
    - conda-forge
dependencies:
    - python>3.5
    - dask
    - xarray
    - netCDF4
    - seaborn
    - psy-maps
    - python-cdo
    - cdo
    - sphinx-argparse
    - sphinx-nbexamples
    - pip
