name: psyplot_docs
channels:
    - chilipp/label/dev
    - conda-forge
dependencies:
    - python=3.6
    - dask
    - xarray
    - netCDF4
    # Use matplotlib < 3.0. Otherwise, cartopy cannot handle it
    - matplotlib<3.0
    - seaborn
    - ipython
    - nbconvert
    - jupyter_client
    - ipykernel
    - sphinx
    - psy-maps
    - sphinx-argparse
    - pip:
        - autodocsumm
        - cdo
        - sphinx-nbexamples
