name: psyplot_docs
channels:
    - chilipp/label/dev
    - conda-forge
dependencies:
    - python=3.7
    - dask
    - xarray
    - netCDF4
    - matplotlib
    - seaborn
    - ipython
    - nbconvert
    - jupyter_client
    - ipykernel
    - sphinx
    - psy-maps
    - sphinx-argparse
    - pip:
        - autodocsumm
        - cdo
        - sphinx-nbexamples
